// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {TeeResultHash} from "../src/libraries/TeeResultHash.sol";

/// @notice Pins the Solidity digest against a fixture produced by Flare's own Go code.
///
/// @dev The fixture was generated by building an `ActionResult` with tee-node's types,
///      hashing it with `ActionResult.Hash()`, domain-separating it with
///      `go-flare-common/pkg/signing.NewPayload(TEEActionResult, 114, dataHash).Hash()`,
///      then hashing once more the way `wallets.Wallet.Sign` does before signing.
///
///      If Flare changes any of those three steps, this test fails loudly instead of the
///      verifier silently rejecting every real verdict on-chain.
contract TeeResultHashTest is Test {
    // ---- fixture, verbatim from the Go run -------------------------------------------
    uint256 constant CHAIN_ID = 114; // Coston2
    bytes32 constant ACTION_ID = 0x1111111111111111111111111111111111111111111111111111111111111111;
    string constant SUBMISSION_TAG = "submit";
    uint8 constant STATUS = 1;
    bytes constant DATA =
        hex"000000000000000000000000000000000000000000000000000000000000b0b00000000000000000000000000000000000000000000000000012bc29d8eb5c0000";

    bytes32 constant EXPECTED_DATA_HASH = 0x970772920272e0255c3130c577dba6613bb52e66077b2e5f2f03e405ab4e9143;
    bytes32 constant EXPECTED_DIGEST = 0x4c3f0c41d154eeaed50490fb11cb97804c2a507de8b54e876bafef1455dd40a6;
    address constant EXPECTED_SIGNER = 0x27000F84214f79B0600aa86841958b13ac98242a;
    bytes constant SIGNATURE =
        hex"865c3fb4ef7781933eecdd74b272aed712a99bb398d651fc5ad33ec91788ca412f986317723a4986fe1157faba0b21560d8bd92522c0e07a6070360cbbc072bb00";
    // -----------------------------------------------------------------------------------

    function testPrefixMatchesGoConstant() public pure {
        // signing.TEEActionResult, an ASCII string right-padded into 32 bytes.
        assertEq(
            TeeResultHash.PREFIX_ACTION_RESULT,
            bytes32(0x5445455f414354494f4e5f524553554c54000000000000000000000000000000)
        );
    }

    function testActionResultHashMatchesGo() public pure {
        assertEq(TeeResultHash.actionResultHash(DATA, ACTION_ID, SUBMISSION_TAG, STATUS), EXPECTED_DATA_HASH);
    }

    /// @dev Catches the mistake of stopping after the domain separation and forgetting that
    ///      `Wallet.Sign` hashes its argument again.
    function testSignedDigestMatchesGo() public pure {
        assertEq(TeeResultHash.digest(DATA, ACTION_ID, SUBMISSION_TAG, STATUS, CHAIN_ID), EXPECTED_DIGEST);
    }

    /// @dev The end-to-end proof: a signature produced by geth's crypto.Sign recovers to the
    ///      expected address using only the digest this library computes.
    function testGoSignatureRecoversOnChain() public pure {
        bytes32 d = TeeResultHash.digest(DATA, ACTION_ID, SUBMISSION_TAG, STATUS, CHAIN_ID);

        bytes memory sig = SIGNATURE;
        bytes32 r;
        bytes32 s;
        uint8 v;
        assembly {
            r := mload(add(sig, 32))
            s := mload(add(sig, 64))
            v := byte(0, mload(add(sig, 96)))
        }
        // geth yields recovery id 0/1; ecrecover wants 27/28.
        assertEq(v, 0, "fixture should carry a raw geth recovery id");
        v += 27;

        assertEq(ecrecover(d, v, r, s), EXPECTED_SIGNER);
    }

    /// @dev Chain binding is the point of the domain separator: the same result signed for
    ///      Coston2 must not verify against Flare mainnet.
    function testDigestIsBoundToChainId() public pure {
        bytes32 coston2 = TeeResultHash.digest(DATA, ACTION_ID, SUBMISSION_TAG, STATUS, 114);
        bytes32 flare = TeeResultHash.digest(DATA, ACTION_ID, SUBMISSION_TAG, STATUS, 14);
        assertTrue(coston2 != flare);
    }

    /// @dev And so is tag binding: a "threshold" result must not pass as a "submit" one.
    function testDigestIsBoundToSubmissionTag() public pure {
        bytes32 submit = TeeResultHash.digest(DATA, ACTION_ID, SUBMISSION_TAG, STATUS, CHAIN_ID);
        bytes32 threshold = TeeResultHash.digest(DATA, ACTION_ID, "threshold", STATUS, CHAIN_ID);
        assertTrue(submit != threshold);
    }
}
